# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160627_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titl',
            new_name='title',
        ),
    ]
