# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160627_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='New Notification', max_length=200),
        ),
    ]
