# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160627_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Version',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='release',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='remarks',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='technology',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
